[package]
name = "coroutines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = {version = "1.0.2", features = ["net", "os-poll"]}
